# Anomaly Detection

## Isolation Forest

Isolation forest is a machine learning algorithm for anomaly detection.
It's an unsupervised learning algorithm that identifies anomaly by isolating outliers in the data.

Isolation Forest is based on the Decision Tree algorithm. It isolates the outliers by randomly selecting a feature from the given set of features and then randomly selecting a split value between the max and min values of that feature. This random partitioning of features will produce shorter paths in trees for the anomalous data points, thus distinguishing them from the rest of the data.

In general the first step to anomaly detection is to construct a profile of what's "normal", and then report anything that cannot be considered normal as anomalous. However, the isolation forest algorithm does not work on this principle; it does not first define "normal" behavior, and it does not calculate point-based distances.

https://blog.paperspace.com/anomaly-detection-isolation-forest/

In [16]:
from sklearn.ensemble import IsolationForest

model_IF = IsolationForest(contamination=float(0.5), random_state=42)
model_IF.fit(X_train)

isolated = X_train.copy()
isolated['anomaly_scores'] = model_IF.decision_function(X_train)
isolated['anomaly'] = model_IF.predict(X_train)
isolated.head()

C:\Users\cliff\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,anomaly_scores,anomaly
484230,0,1,21,1,0,0,0,0,0,0,...,1.00,0.00,0.00,0.01,0.00,0.01,0.14,0.13,-0.073356,-1
140849,0,1,36,1,0,0,0,0,0,0,...,0.00,1.00,0.00,0.00,0.18,0.00,0.82,1.00,-0.281294,-1
343141,0,2,40,9,105,146,0,0,0,0,...,0.96,0.01,0.00,0.00,0.00,0.00,0.00,0.00,-0.000480,-1
26168,0,1,21,9,206,7355,0,0,0,0,...,1.00,0.00,0.07,0.02,0.00,0.00,0.00,0.00,0.026158,1
139864,0,1,21,9,289,1959,0,0,0,0,...,1.00,0.00,0.50,0.03,0.00,0.00,0.00,0.00,0.001864,1

In [17]:
# Print out key statistics
print(f"Number of anomalous values {len(isolated[isolated['anomaly']==-1])}")
print(f"Number of non anomalous values  {len(isolated[isolated['anomaly']== 1])}")
print(f'Total Number of Values: {len(isolated)}')

Number of anomalous values 41608
Number of non anomalous values  41608
Total Number of Values: 83216

In [18]:
isolated['outcome'] = y_train

In [19]:
isolated[isolated['anomaly']==  -1].head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,anomaly_scores,anomaly,outcome
484230,0,1,21,1,0,0,0,0,0,0,...,0.00,0.00,0.01,0.00,0.01,0.14,0.13,-0.073356,-1,1
140849,0,1,36,1,0,0,0,0,0,0,...,1.00,0.00,0.00,0.18,0.00,0.82,1.00,-0.281294,-1,2
343141,0,2,40,9,105,146,0,0,0,0,...,0.01,0.00,0.00,0.00,0.00,0.00,0.00,-0.000480,-1,1
344072,0,1,21,1,0,0,0,0,0,0,...,0.00,0.02,0.08,0.00,0.00,1.00,1.00,-0.092114,-1,1
143495,0,2,10,9,36,96,0,0,0,0,...,0.02,0.00,0.00,0.00,0.00,0.00,0.00,-0.019969,-1,1

In [20]:
isolated[isolated['anomaly']==  -1]['outcome'].value_counts().sort_index()

0     1183
1    36216
2     3265
3      901
4       43
Name: outcome, dtype: int64

### Categories of Attacks

* 0 - DOS: Denial of Service 
* 1 - Normal
* 2 - probing (Brute-force probing attacks)
* 3 - R2L (Unauthorized accesses from remote servers)
* 4 - U2R (Privilege escalation attempts): Exploitation of vulnerabilities such as software bugs, misconfigurations, and incorrect access controls

https://kdd.ics.uci.edu/databases/kddcup99/task.html

In [21]:
isolated[isolated['anomaly']==  1].head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,anomaly_scores,anomaly,outcome
26168,0,1,21,9,206,7355,0,0,0,0,...,0.0,0.07,0.02,0.0,0.0,0.0,0.00,0.026158,1,1
139864,0,1,21,9,289,1959,0,0,0,0,...,0.0,0.50,0.03,0.0,0.0,0.0,0.00,0.001864,1,1
7100,0,1,21,9,331,612,0,0,0,0,...,0.0,0.02,0.02,0.0,0.0,0.0,0.00,0.034677,1,1
107287,0,1,21,9,346,11319,0,0,0,0,...,0.0,0.02,0.02,0.0,0.0,0.0,0.01,0.023858,1,1
15366,0,1,21,9,206,945,0,0,0,0,...,0.0,0.01,0.03,0.0,0.0,0.0,0.00,0.026174,1,1

In [22]:
isolated[isolated['anomaly']==  1]['outcome'].value_counts().sort_index()

1    41608
Name: outcome, dtype: int64

### Categories of Attacks

* 0 - DOS: Denial of Service 
* 1 - Normal
* 2 - probing (Brute-force probing attacks)
* 3 - R2L (Unauthorized accesses from remote servers)
* 4 - U2R (Privilege escalation attempts): Exploitation of vulnerabilities such as software bugs, misconfigurations, and incorrect access controls

https://kdd.ics.uci.edu/databases/kddcup99/task.html