# Association Rules

## Apriori 

* https://towardsdatascience.com/the-apriori-algorithm-5da3db9aea95
* https://towardsdatascience.com/apriori-algorithm-for-association-rule-learning-how-to-find-clear-links-between-transactions-bf7ebc22cf0a

Market Basket Analysis

Association rule mining is a widely used technique for discovering relationships between variables in a large data set (e.g., items in a store that are commonly purchased together). The classic market basket analysis example using association rules is the "beer and diapers" rule. According to a data mining urban legend, a study of customer purchase behavior in a supermarket found that men often purchased beer and diapers together. After making this discovery, the managers strategically placed beer and diapers closer together on the shelves and saw a dramatic increase in sales. In addition to market basket analysis, association rules are also used in bioinformatics, web analytics, and several other fields.

https://madlib.apache.org/docs/latest/group__grp__assoc__rules.html

In another tactic, managers may distance milk and bread so that customers are forced to walk through more aisles and see more products.

Apriori: If you do something, do you do something else? What is this something and something else?

### Rules

x => y: when does x and y appear together; when you have x, will you also have y; when you buy x, will you buy y

* Count: The number of transactions that contain x and y
* Support: Percentage of times the items appear together. Transaction of x and y / all transactions 
* Confidence: Percentage of transactions where this rule is valid. The ratio of transactions that contain x and y to transactions that contain x. One could view this metric as  p(x | y) or confidence(x => y).
* Lift: The strength of the association. The ratio of observed support(x +> y) to the expected support of x and y , assuming x and y are independent. lift(x => y) = support(x => y) / (support(x) * support(y)), or $p(x \cap y) / (p(x) * p(y))$
* Conviction: How sure are we? conviction(x => y) = (1 - support(x => y)) / (1 - confidence(x => y))

### Explanations

* https://madlib.apache.org/docs/latest/group__grp__assoc__rules.html
* https://www.kdnuggets.com/2016/04/association-rules-apriori-algorithm-tutorial.html
* https://towardsdatascience.com/the-apriori-algorithm-5da3db9aea95

In [1]:
# !pip install apyori

In [2]:
# super datascience center
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/gitmystuff/Datasets/main/Market_Basket_Optimisation.csv', header = None)
transactions = []
for i in range(0, 7501):
    transactions.append([str(df.values[i,j]) for j in range(0, 20)])
    
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# build rules
from apyori import apriori

rules = apriori(transactions = transactions, 
                min_support = 0.003, 
                min_confidence = 0.2, 
                min_lift = 3, 
                min_length = 2, 
                max_length = 2)

In [4]:
# display results
results = list(rules)

def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports, confidences, lifts))

analysis = pd.DataFrame(inspect(results), columns = ['Left Hand Side', 'Right Hand Side', 'Support', 'Confidence', 'Lift'])
analysis.nlargest(n = 10, columns = 'Lift')

         Left Hand Side Right Hand Side   Support  Confidence      Lift
3         fromage blanc           honey  0.003333    0.245098  5.164271
0           light cream         chicken  0.004533    0.290598  4.843951
2                 pasta        escalope  0.005866    0.372881  4.700812
8                 pasta          shrimp  0.005066    0.322034  4.506672
7     whole wheat pasta       olive oil  0.007999    0.271493  4.122410
5          tomato sauce     ground beef  0.005333    0.377358  3.840659
1  mushroom cream sauce        escalope  0.005733    0.300699  3.790833
4         herb & pepper     ground beef  0.015998    0.323450  3.291994
6           light cream       olive oil  0.003200    0.205128  3.114710

### Rules

x => y: when does x and y appear together; when you have x, will you also have y; when you buy x, will you buy y

* Count: The number of transactions that contain x and y
* Support: Percentage of times the items appear together. Transaction of x and y / all transactions 
* Confidence: Percentage of transactions where this rule is valid. The ratio of transactions that contain x and y to transactions that contain x. One could view this metric as  p(x | y) or confidence(x => y).
* Lift: The strength of the association. The ratio of observed support(x +> y) to the expected support of x and y , assuming x and y are independent. lift(x => y) = support(x => y) / (support(x) * support(y)), or $p(x \cap y) / (p(x) * p(y))$

## ECLAT

Equivalence Class Clustering and Bottom-Up Lattice Traversal

https://towardsdatascience.com/the-eclat-algorithm-8ae3276d2d17

Unlike the apriori method, the ECLAT method is not based on the calculation of confidence and lift, therefore the ECLAT method is based on the calculation of the support conjunctions of the variables.

https://pypi.org/project/pyECLAT/

* ECLAT focuses on support
* Faster with fewer metrics

Eclat is an algorithm for finding frequent item sets in a transaction or database. It is one of the best methods of Association Rule Learning. Which means Eclat algorithm is used to generate frequent item sets in a database.

https://www.i2tutorials.com/machine-learning-tutorial/machine-learning-eclat-algorithm/

In [5]:
# !pip install pyECLAT

In [6]:
# https://hands-on.cloud/implementation-of-eclat-algorithm-using-python/
from pyECLAT import ECLAT

min_n_products = 2
min_support = .03
max_length = 2

analysis = ECLAT(data=df, verbose=True)
_, rule_supports = analysis.fit(min_support=.03,
                                           min_combination=2,
                                           max_combination=2)

100%|███████████████████████████████████████████████████████████████████████████████| 120/120 [00:00<00:00, 123.30it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 120/120 [00:00<00:00, 5894.88it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 120/120 [00:00<00:00, 3033.34it/s]

Combination 2 by 2

630it [00:03, 165.36it/s]

In [7]:
import pandas as pd

eclat_df = pd.DataFrame(rule_supports.items(), columns=['items', 'support'])
eclat_df.sort_values(by=['support'], ascending=False).head(10)

                                items   support
8           mineral water & spaghetti  0.059725
1           mineral water & chocolate  0.052660
4                mineral water & eggs  0.050927
2                mineral water & milk  0.047994
5         mineral water & ground beef  0.040928
17            ground beef & spaghetti  0.039195
13              chocolate & spaghetti  0.039195
16                   eggs & spaghetti  0.036528
10                french fries & eggs  0.036395
3   mineral water & frozen vegetables  0.035729