# Data

## Data Science Process

https://www.springboard.com/blog/data-science/data-science-process/

## Data

According to Wikipedia (2023):

>  In the pursuit of knowledge, data is a collection of discrete values that convey information, describing quantity, quality, fact, statistics, other basic units of meaning, or simply sequences of symbols that may be further interpreted. A datum is an individual value in a collection of data. Data is usually organized into structures such as tables that provide additional context and meaning, and which may themselves be used as data in larger structures (para 1).
 
Data. (2023, January 23). In *Wikipedia*. https://en.wikipedia.org/wiki/Data

Data are dumb. Data needs context. 

* GPA, used a lot but doesn't count the difficulty of the courses taken

* It was found that workers who take frequent breaks died earlier than others
    * That's because they were out smoking

### Data Needs to be Reliable

* Consistency of a measure (whether the results can be reproduced under the same conditions)

### Data Needs to be Valid

* The accuracy of a measure (whether the results really do represent what they are supposed to measure)

### Precision vs Accuracy

* Precision: exactitude of describing something
* Accuracy: how consistent to the truth
* Where's the library? About 1.6 miles from here (precise but not to useful) vs. go down this street a couple of blocks till you pass a bank. It'll be to the right. If you pass the fire station, you've gone too far

### Statistical Models for Data

* A formal representation of relationships between variables we use to describe or explain something

## Data Starts with a Question

According to Wikipedia (2022):

>  A research question is a question that a research project sets out to answer'. Choosing a research question is an essential element of both quantitative and qualitative research. Investigation will **require data collection and analysis**, and the methodology for this will vary widely. Good research questions seek to improve knowledge on an important topic, and are usually narrow and specific (para 1).

Research Question. (2022, January 24). In *Wikipedia*. https://en.wikipedia.org/wiki/Research_question

### Parameter vs Statistic 

* https://www.statisticshowto.com/statistics-basics/how-to-tell-the-difference-between-a-statistic-and-a-parameter/ 
* Parameter describes population, statistic describes sample

### Statistical Inference

According to Wikipedia (2022):

>  the process of using data analysis to infer properties of an underlying distribution of probability (para 1).

Statistical Inference. (2022, January 24). In *Wikipedia*. https://en.wikipedia.org/wiki/Statistical_inference.

https://www.analyticsvidhya.com/blog/2022/03/an-overview-of-data-collection-data-sources-and-data-mining/

* Mean and standard deviation of a sample should be similar to the mean and standard deviation of the population
* Mean: where most of the observations lie with a distribution variance that is symmetrical
* Standard Deviation: a way to measure how far observations are from the mean, on the x axis, in terms similar to the data it represents

## Data Considerations


### Garbage In Garbage Out (GIGO)

GI of GIGO

* Wrong
* Too Different
* Too Similar
* Missing
* Terrible statistical assertions result from good statistical methods applied to bad samples

### Data Perspectives

https://www.bbc.com/news/science-environment-17357560

* The study possibly suggests a connection between stress and chemical responses
* The real winner is the data, a group of satiated males and a group of frustrated males
* Data are to statistics what the front line is to the quarterback

### Data Needs Three Things

1. The sample is representative of the population
    * One way to achieve this is through simple random sample
    * Larger the better
    * A representative sample opens possibilities from a hundred years of statistical methods
    * Getting a good sample isn't easy
2. Data should show comparison
    * Differences between groups
    * Does a method improve something
    * In the movie Caddyshack, golf related comedy, Chevy Chase is asked how his scores compare with others
        * I really don't keep score
        * But then how do you compare with others
        * By height
3. Sometimes we collect data just because
    * Like a crime scene, collect all the clues you can find
    * Data are like clues

## Data Types

* Numerical: has measurement
    * Discrete: can be counted (number of people in a class)
    * Continuous: described as a measurement (height, weight, temps), usually rounded off
* Categorical: some type of group, category, that can be represented by a number (female: 1, male: 2) but have no mathematical meaning
* Nominal: named or labeled (31 flavors)
* Ordinal: ordered or scaled (first, second, etc, very happy, happy, meh, sad, very sad)
* Cardinal: the number of things, counted (1, 2, 3, 4, 6, etc)
* Interval: ordered numbers with equal distances (50 degrees, 60 degrees, etc)
* Ratio: has a true zero (can't have height of -2 inches, distance between 1 and 2 is the same as 3 and 4 and 4 is twice 2)

## Sampling

According to Wikipedia (2022):

>  Sampling is the selection of a subset (a statistical sample) of individuals from within a statistical population [similar elements] to estimate characteristics of the whole population (para 1).

Sampling. (2022, January 24). In *Wikipedia*.https://en.wikipedia.org/wiki/Sampling_(statistics)

### Probabilistic Sampling

* Simple random sampling: https://www.statisticshowto.com/probability-and-statistics/statistics-definitions/simple-random-sample/
* Systematic sampling: https://www.open.edu/openlearncreate/mod/oucontent/view.php?id=233&section=1.5.2
* Stratified sampling: https://www.geeksforgeeks.org/stratified-sampling-in-pandas/
* Clustering: https://www.voxco.com/blog/stratified-sampling-vs-cluster-sampling/

### Non-Probabilistic Sampling Methods

https://www.analyticsvidhya.com/blog/2019/09/data-scientists-guide-8-types-of-sampling-techniques/
* Convenience sampling
* Quota sampling
* Snowball sampling

### Avoid Getting Biased Data

* Selection bias: How did a politician win?
* Publication bias: Video games do not cause colon cancer vs. spending a lot of time playing video games do have a lower incidence of colon cancer
* Recall bias: Memory is selective
* Survivorship bias: Students did better on tests each of their four years (those that didn't do so well dropped out)

## Data Resources

### Sklearn

* https://scikit-learn.org/stable/datasets.html

In [1]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 20640\n\n    :Number of Attributes: 8 numeric, predictive attributes and the target\n\n    :Attribute Information:\n        - MedInc        median income in block group\n        - HouseAge      median house age in block group\n        - AveRooms      average number of rooms per household\n        - AveBedrms     average number of bedrooms per household\n        - Population    block group population\n        - AveOccup      average number of household members\n        - Latitude      block group latitude\n        - Longitude     block group longitude\n\n    :Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nAn household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surpinsingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. topic:: References\n\n    - Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n      Statistics and Probability Letters, 33 (1997) 291-297\n'}

In [2]:
# get keys
housing.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [3]:
# get description
print(housing.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

An household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surpinsingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. topic:: References

    - Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
      Statistics and Probability Letters, 33 (1997) 291-297

In [4]:
print(housing.feature_names)
print(housing.target_names) # create housing dataframe
import pandas as pd

housing_df = pd.DataFrame(housing.data, columns=housing.feature_names)
housing_df['MedHouseVal'] = housing.target
housing_df.head()

['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']
['MedHouseVal']

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [5]:
# alternative method
X, y = fetch_california_housing(return_X_y=True)
X_housing = pd.DataFrame(X, columns=housing.feature_names)
X_housing.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

### Seaborn

* https://seaborn.pydata.org/generated/seaborn.load_dataset.html

In [6]:
# get list of seaborn datasets
import seaborn as sns

sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [7]:
# loading seaborn dataset
mpg = sns.load_dataset('mpg')
mpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [8]:
# look at origin labels
mpg['origin'].unique()

array(['usa', 'japan', 'europe'], dtype=object)

### Online Repositories
* https://archive.ics.uci.edu/ml/datasets/Auto+MPG
* http://lib.stat.cmu.edu/datasets/
* https://www.kaggle.com/datasets

### .csv

In [9]:
advertising = pd.read_csv('https://raw.githubusercontent.com/gitmystuff/Datasets/main/Advertising.csv')
advertising.head()

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [10]:
advertising = pd.read_csv('https://raw.githubusercontent.com/gitmystuff/Datasets/main/Advertising.csv', usecols=['TV', 'radio', 'newspaper', 'sales'])
advertising.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

### .data

In [11]:
# sep data example; https://archive.ics.uci.edu/ml/datasets/auto+mpg 
cars = pd.read_csv('https://raw.githubusercontent.com/gitmystuff/Datasets/main/auto-mpg.data', sep = '\s+', header = None)
cars.columns=['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year', 'origin',  'car name']
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

### Simulated Data

In [12]:
# example with make_regression
from sklearn.datasets import make_regression

X, y = make_regression(n_samples=100, n_features=1, noise=50)
sim_df = pd.DataFrame({'X': X.flatten(), 'y': y})
sim_df.head()

          X          y
0  1.140240 -25.423162
1  1.637047  16.597069
2 -1.694898  67.669014
3  0.719646 -33.945578
4  1.398585  98.193132

### Using a Codebook

https://www.kaggle.com/rhuebner/human-resources-data-set<br />
https://rpubs.com/rhuebner/hrd_cb_v14

### Data Resource List

* https://vincentarelbundock.github.io/Rdatasets/articles/data.html
* pip install rdatasets
* from rdatasets import data as rdata
* https://www.statsmodels.org/devel/datasets/index.html 
* https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research
* https://archive.ics.uci.edu/ml/datasets/Auto+MPG
* http://lib.stat.cmu.edu/datasets/
* https://www.kaggle.com/datasets
* https://registry.opendata.aws/
* https://dataportals.org/
* https://opendatamonitor.eu/frontend/web/index.php?r=dashboard%2Findex
* https://data.nasdaq.com/
* http://radar.oreilly.com/2011/01/journalist-data-tools.html
* https://www.reddit.com/r/datasets/
* https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/00Index.html
* https://github.com/vincentarelbundock/Rdatasets 
* https://data.world/ 
* https://data.gov/
* https://registry.opendata.aws/
* https://cloud.google.com/datasets
* https://cloud.google.com/bigquery/public-data
* https://services.google.com/fh/files/misc/public_datasets_one_pager.pdf

### Excel: Text to Column

* Download the student.zip file from http://archive.ics.uci.edu/ml/machine-learning-databases/00320/ 
* Unzip to an appropriate folder, and open student-mat.csv in Excel (HINT: Right-click on student-mat.csv and choose Open with Excel) 
* Save this file as student-mat.xlsx 
* Use Text to Column to format data
* HINT: select all the data in the first column before using Text to Column and then use the semicolon as the Delimiter